import { customAlphabet } from "nanoid";

const digits = customAlphabet("0123456789", 6);
const tokenAlphabet = customAlphabet(
  "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789",
  24
);

/**
 * Client-side preview only — the authoritative code is generated by
 * generate_report_code() in Postgres at insert time, which also
 * guarantees uniqueness. This is used for optimistic UI / testing.
 */
export function previewReportCode(prefix = "TDB") {
  const year = new Date().getFullYear();
  return `${prefix}-${year}-${digits()}`;
}

export function previewTrackingToken() {
  return tokenAlphabet();
}
